### ISSUE TITLE
Add metadata about the information of GPIs

### ISSUE THREAD

**Issue by xushanthu-2014** [VegeWaterDynamics/motrainer#63]
Maybe it's possible to add a metadata to show some brief information of GPI on which the ml_model is trained? For example, the lat&lon, vegetation fraction, max vegetation fraction, mean value and std value of sig&slop&curv, and also mean&std value of each input variable? Thanks!

**Comment by rogerkuou** [comment]
redefined the task in #104.

IMO, after we implemented the input data with `xrarray.Dataset`, all the grid-related data without temporal dimension can also be persisted in the Dataset (instead of a nested DataFrame). Therefore a solution for this can be present a space/time coordinates and path to the original data file.
